export const formConfig = {
  background: '#EFEFEF',
  colon: false,
  cssCode: '',
  customClass: '',
  dataSources: [],
  functions: '',
  inputAlign: 'left',
  inputBorder: false,
  jsonVersion: -3,
  labelAlign: 'left',
  labelPosition: 'left',
  labelWidth: 80,
  layoutType: 'H5',
  modelName: 'formData',
  onFormCreated: '',
  onFormDataChange: '',
  onFormMounted: '',
  onFormValidate: '',
  padding: 5,
  popupZIndex: 3000,
  radius: 4,
  refName: 'vForm',
  rulesName: 'rules',
  size: '',
  dynamicLogicList: [],
}
export const widgetList = [
  {
    key: 51835,
    formItemFlag: true,
    icon: 'radio-field',
    options: {
      customClass: '',
      defaultValue: null,
      desc: '11111',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      dataName: '',
      hidden: false,
      iconSize: '20',
      label: 'm-radio',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'mradio18135',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '选项1',
          value: 1,
          exampleImage: '',
          tooltip: '选项1提示信息',
          image: '',
          additionalOption: null,
        },
        {
          label: '选项2',
          value: 2,
          exampleImage: 'http://gips1.baidu.com/it/u=3874647369,3220417986&fm=3028&app=3028&f=JPEG&fmt=auto?w=720&h=1280',
          tooltip: '',
          image: '',
          additionalOption: null,
        },
        {
          label: '多附加',
          value: 3,
          exampleImage: '',
          tooltip: '',
          image: '',
          additionalOption: null,
          hasAdditionalComponents: true,
          disabled: false,
          hidden: false,
          additionalComponents: [
            {
              id: 43619,
              label: '输入',
              name: 'component1',
              type: 'input',
              required: true,
              defaultValue: '',
              requiredMessage: '必填提示：',
              placeholder: 'component1',
              options: [],
              simpleOptions: [],
            },
            {
              id: 111656,
              label: '',
              name: 'component2',
              type: 'select',
              required: true,
              defaultValue: null,
              requiredMessage: '',
              placeholder: 'component2',
              options: [
                {
                  id: 104251,
                  label: '新选项1',
                  value: 'new_option1',
                  isGroup: false,
                },
                {
                  id: 77480,
                  label: '新选项2',
                  value: 'new_option2',
                  isGroup: false,
                },
                {
                  id: 9059,
                  label: '新选项3',
                  value: 'new_option3',
                  isGroup: false,
                },
              ],
              simpleOptions: [],
            },
          ],
          additionalComponentsMultiple: true,
          maxAdditionalComponents: 2,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
    },
    type: 'm-radio',
    id: 'mradio18135',
  },
  {
    key: 101613,
    formItemFlag: true,
    icon: 'checkbox-field',
    options: {
      customClass: '',
      defaultValue: null,
      desc: '',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: 'safdasdfasdf',
      dataName: '',
      hidden: false,
      iconSize: '20',
      label: 'm-checkbox',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'mcheckbox23061',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '单面',
          value: 1,
          exampleImage: '',
          tooltip: '单面说明',
          image: '',
          additionalOption: null,
        },
        {
          label: '双面',
          value: 2,
          exampleImage: 'http://gips0.baidu.com/it/u=3602773692,1512483864&fm=3028&app=3028&f=JPEG&fmt=auto?w=960&h=1280',
          tooltip: '',
          image: '',
          additionalOption: null,
        },
        {
          label: '不印',
          value: 3,
          exampleImage: '',
          tooltip: '',
          image: '',
          additionalOption: null,
          disabled: true,
        },
        {
          label: '特殊',
          value: 4,
          exampleImage: 'http://gips0.baidu.com/it/u=3602773692,1512483864&fm=3028&app=3028&f=JPEG&fmt=auto?w=960&h=1280',
          tooltip: '特殊说明',
          image: '',
          disabled: false,
          hidden: false,
          additionalLabel: '',
          additionalType: '',
          additionalOptions: '',
          additionalPlaceholder: '',
          hasAdditionalComponents: true,
          additionalComponents: [
            {
              id: 43619,
              label: '组件1',
              name: 'component1',
              type: 'input',
              required: true,
              requiredMessage: '',
              defaultValue: '',
              placeholder: 'component1',
              options: [],
              simpleOptions: [],
            },
            {
              id: 111656,
              label: '组件2',
              name: 'component2',
              type: 'select',
              required: true,
              requiredMessage: '',
              defaultValue: null,
              placeholder: '',
              options: [
                {
                  id: 104251,
                  label: '新选项1',
                  value: 'new_option1',
                  isGroup: false,
                },
                {
                  id: 77480,
                  label: '新选项2',
                  value: 'new_option2',
                  isGroup: false,
                },
                {
                  id: 9059,
                  label: '新选项3',
                  value: 'new_option3',
                  isGroup: false,
                },
              ],
              simpleOptions: [],
            },
          ],
          additionalComponentsMultiple: true,
          maxAdditionalComponents: 3,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
    },
    type: 'm-checkbox',
    id: 'mcheckbox23061',
  },
  {
    key: 50892,
    formItemFlag: true,
    icon: 'datetime-field',
    options: {
      clearable: true,
      customClass: '',
      defaultValue: null,
      desc: '',
      disabled: false,
      editable: false,
      format: 'YYYY-MM-DD HH:mm',
      hidden: false,
      label: 'm-datetime',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelTooltip: null,
      labelWidth: null,
      maxDate: '',
      minDate: '',
      name: 'mdatetime92090',
      onBlur: '',
      onChange: '',
      onConfirm: '',
      onCreated: '',
      onFocus: '',
      onMounted: '',
      onValidate: '',
      placeholder: '',
      readonly: false,
      required: false,
      requiredHint: '',
      size: '',
      validation: '',
      validationHint: '',
    },
    type: 'm-datetime',
    id: 'mdatetime92090',
  },
  {
    key: 46223,
    formItemFlag: true,
    icon: 'select-field',
    options: {
      clearable: true,
      customClass: '',
      defaultValue: null,
      desc: '',
      disabled: false,
      dropdownMode: 'picker',
      dsEnabled: false,
      dsName: '',
      dataName: '',
      filterable: false,
      hidden: false,
      label: 'm-select',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      multiple: false,
      name: 'mselect55755',
      onBlur: '',
      onChange: '',
      onCreated: '',
      onFocus: '',
      onMounted: '',
      onRemoteQuery: '',
      onValidate: '',
      optionItems: [
        {
          label: 'select 1',
          value: 1,
        },
        {
          label: 'select 2',
          value: 2,
        },
        {
          label: 'select 3',
          value: 3,
        },
      ],
      placeholder: '',
      readonly: false,
      remote: false,
      required: false,
      requiredHint: '',
      size: '',
      valueKey: 'value',
    },
    type: 'm-select',
    id: 'mselect55755',
  },
  {
    key: 108320,
    formItemFlag: true,
    icon: 'size-field',
    options: {
      desc: '',
      customClass: '',
      defaultValue: {
        width: '',
        height: '',
      },
      disabled: false,
      hidden: false,
      label: '尺寸',
      labelAlign: '',
      labelHidden: false,
      labelWidth: null,
      name: 'msize59814',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      readonly: false,
      required: false,
      requiredHint: '',
      validation: '',
      validationHint: '',
      widthPlaceholder: '请输入宽度(MM)',
      heightPlaceholder: '请输入高度(MM)',
      clearable: true,
      inputAlign: 'left',
      size: '',
      onChange: '',
      onBlur: '',
      onFocus: '',
      onInput: '',
    },
    type: 'm-size',
    id: 'msize59814',
  },
   {
      "key": 55667,
      "formItemFlag": false,
      "icon": "button",
      "options": {
        "customClass": "",
        "desc": "",
        "displayStyle": "block",
        "hidden": false,
        "label": "报价组件",
        "name": "mquote104303",
        "onCreated": "",
        "onMounted": "",
        "quantities": [
          10,
          20,
          50,
          200,
          300
        ],
        "officalOrderPrice": [
          10,
          20,
          null,
          200,
          300
        ],
        "manualOrderPrice": [
          10,
          20,
          200,
          null,
          300
        ],
        "showOfficialOrder": true,
        "showManualOrder": true,
        "quoteApiUrl": "/api/quote"
      },
      "type": "m-quote",
      "id": "mquote104303"
    }
]
