export const formConfig = {
  background: '#FFFFFF',
  colon: false,
  cssCode:
    ".field-label-with-desc{\r\n  display: inline-block;\r\n  width: 100%;\r\n  padding: 4px 0px;\r\n  text-align: center;\r\n  font-size: 14px;\r\n  font-family: Arial, sans-serif;\r\n  color: #333;\r\n  background-color: #f0f0f0;\r\n  border: none;\r\n  border-radius: 4px;\r\n}\r\n.content-title,.subform-label{\r\n  position:relative;\r\n  font-weight: bold;\r\n  font-size:16px;\r\n  padding:15px 0px;\r\n  padding-left:25px;\r\n  box-sizing: border-box;\r\n}\r\n.content-title::before,.subform-label::before{\r\n  content: '';\r\n  left: 15px;\r\n  top: 10px;\r\n  bottom: 10px;\r\n  border-left: solid 6px #FFEC5A;\r\n  border-radius: 2px;\r\n  position: absolute;\r\n}\r\n",
  customClass: [],
  dataSources: [],
  functions: '',
  inputAlign: 'right',
  inputBorder: false,
  jsonVersion: -3,
  labelAlign: 'left',
  labelPosition: 'left',
  labelWidth: 80,
  layoutType: 'PC',
  modelName: 'formData',
  onFormCreated: '',
  onFormDataChange: '',
  onFormMounted: '',
  onFormValidate: '',
  padding: 5,
  popupZIndex: 3000,
  radius: 4,
  refName: 'vForm',
  rulesName: 'rules',
  size: '',
  h5LabelTop: true,
  gridResponsive: true,
  formName: '印刷品表单',
  formDes: '根据图片生成的表单',
  dynamicLogicList: [
    {
      triggerFieldName: 'binding',
      triggerFieldValues: ['裸背无线胶装'],
      actions: [
        {
          targetFieldName: 'craft',
          type: 'setOptionEnable',
          value: [
            {
              optionValue: '书脊',
              state: false,
            },
          ],
        },
        {
          targetFieldName: 'msize92125',
          type: 'setVisibility',
          value: true,
        },
        {
          targetFieldName: 'wholeBookProcess',
          type: 'setVisibility',
          value: true,
        },
      ],
      elseActions: [
        {
          targetFieldName: 'craft',
          type: 'setOptionEnable',
          value: [
            {
              optionValue: '书脊',
              state: true,
            },
          ],
        },{
            "targetFieldName": "msize92125",
            "type": "setVisibility",
            "value": true
          }
      ],
    },
    {
      triggerFieldName: 'mcascader82789',
      triggerFieldValues: [250],
      actions: [
        {
          targetFieldName: 'mcheckbox19662',
          type: 'setOptionEnable',
          value: [
            {
              optionValue: '现调纸',
              state: false,
            },
            {
              optionValue: '印刷机型',
              state: false,
            },
          ],
        },
      ],
      elseActions: [],
    },
    {
      triggerFieldName: 'mcascader82789',
      triggerFieldValues: [157],
      actions: [
        {
          targetFieldName: 'mcheckbox78929',
          type: 'setOptionEnable',
          value: [
            {
              optionValue: 2,
              state: false,
            },
            {
              optionValue: 3,
              state: false,
            },
            {
              optionValue: 3,
              state: false,
            },
            {
              optionValue: 5,
              state: false,
            },
            {
              optionValue: 6,
              state: false,
            },
            {
              optionValue: 8,
              state: false,
            },
          ],
        },
        {
          targetFieldName: 'mcheckbox16669',
          type: 'setEnable',
          value: false,
        },
        {
          targetFieldName: 'mcheckbox97184',
          type: 'setEnable',
          value: false,
        },
        {
          targetFieldName: 'mcheckbox102264',
          type: 'setEnable',
          value: false,
        },
        {
          targetFieldName: 'mcheckbox19662',
          type: 'setOptionEnable',
          value: [
            {
              optionValue: '现调纸',
              state: false,
            },
            {
              optionValue: '印刷机型',
              state: false,
            },
          ],
        },
      ],
      elseActions: [],
    },
  ],
}

export const widgetList = [
  {
    key: 26606,
    options: {
      customClass: ['content-title'],
      desc: '静态文本组件，用于显示固定文本内容',
      fontSize: '16px',
      hidden: false,
      name: '公共项',
      onCreated: '',
      onMounted: '',
      textContent: '公共项',
      label: 'm-static-text',
    },
    type: 'm-static-text',
    id: 'mstatictext61697',
    icon: 'static-text',
    formItemFlag: false,
  },
  {
    type: 'm-radio',
    options: {
      customClass: [],
      defaultValue: '',
      desc: '单选框组件，用于在多个选项中选择一个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '装订方式',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'binding',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '无线胶装',
          value: '无线胶装',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/PUR%E6%97%A0%E7%BA%BF%E8%83%B6%E8%A3%8520250427.jpg',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: 'PUR无线胶装',
          value: 'PUR无线胶装',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/PUR%E6%97%A0%E7%BA%BF%E8%83%B6%E8%A3%8520250427.jpg',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: '锁线胶装',
          value: '锁线胶装',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: '裸背无线胶装',
          value: '裸背无线胶装',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: false,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
      dataName: null,
    },
    id: 'mradio106231',
    key: 98756,
    icon: 'radio-field',
    formItemFlag: true,
  },
  {
    key: 21067,
    options: {
      customClass: [],
      defaultValue: {
        width: '',
        height: '',
      },
      disabled: false,
      hidden: false,
      label: '成品尺寸',
      labelAlign: '',
      labelHidden: false,
      labelWidth: null,
      name: 'msize92125',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      readonly: false,
      required: true,
      requiredHint: '请填写尺寸',
      validation: '',
      validationHint: '',
      widthPlaceholder: '装订边',
      heightPlaceholder: '非装订边',
      clearable: true,
      inputAlign: 'left',
      size: '',
      onChange: '',
      onBlur: '',
      onFocus: '',
      onInput: '',
      widthLabel: '宽度',
      heightLabel: '高度',
    },
    type: 'm-size',
    id: 'msize92125',
    icon: 'size-field',
    formItemFlag: true,
  },
  {
    type: 'm-radio',
    options: {
      customClass: [],
      defaultValue: '竖版左翻',
      desc: '单选框组件，用于在多个选项中选择一个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '款式',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'style',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '竖版左翻',
          value: '竖版左翻',
          exampleImage: '',
          tooltip: '',
          image: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E7%AB%96%E7%89%88%E5%B7%A6%E7%BF%BB.png?v=1',
          disabled: false,
        },
        {
          label: '竖版上翻',
          value: '竖版上翻',
          exampleImage: '',
          tooltip: '',
          image: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E7%AB%96%E7%89%88%E4%B8%8A%E7%BF%BB.png?v=1',
          disabled: false,
        },
        {
          label: '横版左翻',
          value: '横版左翻',
          exampleImage: '',
          tooltip: '',
          image: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E6%A8%AA%E7%89%88%E5%B7%A6%E7%BF%BB.png?v=1',
          disabled: false,
        },
        {
          label: '横版上翻',
          value: '横版上翻',
          exampleImage: '',
          tooltip: '',
          image: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E6%A8%AA%E7%89%88%E4%B8%8A%E7%BF%BB.png?v=1',
          disabled: false,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: true,
      valueKey: 'value',
    },
    id: 'mradio23920',
    key: 84337,
    icon: 'radio-field',
    formItemFlag: true,
  },
  {
    type: 'm-checkbox',
    options: {
      customClass: [],
      defaultValue: [],
      desc: '复选框组件，用于在多个选项中选择多个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '必选工艺',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'craft',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '文件设计顺序',
          value: '文件设计顺序',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/huace/huaceshunxusilitu_%200_%201_%20202506011.jpg',
          tooltip: '',
          image: '',
          disabled: false,
          hasAdditionalOption: true,
          additionalLabel: '',
          additionalType: 'select',
          additionalOptions: '选项1,选项1\n选项2,选项2',
          hidden: false,
          hasAdditionalComponents: true,
          additionalComponents: [
            {
              id: 35879,
              label: '',
              name: 'component1',
              type: 'select',
              required: false,
              defaultValue: '',
              placeholder: '',
              options: [
                {
                  id: 57074,
                  label: '类型',
                  isGroup: true,
                  children: [
                    {
                      id: 56011,
                      label: '翻书顺序',
                      value: '1',
                      isGroup: false,
                    },
                  ],
                },
              ],
              simpleOptions: [],
            },
          ],
        },
        {
          label: '书脊',
          value: '书脊',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/huace_shuji_0_20210624.jpg',
          tooltip: '',
          image: '',
          disabled: false,
          hasAdditionalComponents: true,
          hidden: false,
          additionalComponents: [
            {
              id: 20989,
              label: '',
              type: 'select',
              required: false,
              defaultValue: '',
              placeholder: '',
              options: [
                {
                  id: 97644,
                  label: '位置',
                  isGroup: true,
                  children: [
                    {
                      id: 76890,
                      label: '自行调整',
                      value: '1',
                      isGroup: false,
                    },
                    {
                      id: 70703,
                      label: '延伸封面',
                      value: '2',
                      isGroup: false,
                    },
                    {
                      id: 14455,
                      label: '延伸封底',
                      value: '3',
                      isGroup: false,
                    },
                    {
                      id: 27865,
                      label: '已设计',
                      value: '4',
                      isGroup: false,
                    },
                  ],
                },
              ],
              simpleOptions: [],
              name: '书脊',
            },
          ],
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: true,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
      dataName: null,
    },
    id: 'mcheckbox60049',
    key: 36677,
    icon: 'checkbox-field',
    formItemFlag: true,
  },
  {
    type: 'm-checkbox',
    options: {
      customClass: [],
      defaultValue: [],
      desc: '复选框组件，用于在多个选项中选择多个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '增值服务',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'valueAddedServices',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '免费调用',
          value: '免费调用',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E5%85%8D%E8%B4%B9%E8%B0%83%E5%9B%BE-204240814.jpg',
          tooltip: '专供Lv6、Lv8高等级会员图像调整的服务，使图像更符合用纸及印刷要求，整体印品效果更佳;不回传，工期顺延1天。',
          image: '',
          disabled: false,
          hasAdditionalComponents: false,
          hidden: false,
          additionalComponents: [],
          additionalComponentsMultiple: false,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
    },
    id: 'mcheckbox61381',
    key: 38820,
    icon: 'checkbox-field',
    formItemFlag: true,
  },
  {
    type: 'm-checkbox',
    options: {
      customClass: '',
      defaultValue: [],
      desc: '复选框组件，用于在多个选项中选择多个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '整本工艺',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelPosition:'top',
      labelWidth: null,
      name: 'wholeBookProcess',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '整本压油',
          value: '整本压油',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: '整本光油',
          value: '整本光油',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: '整本圆角',
          value: '整本圆角',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/jiaoyinhuace_zhengshuyuanjiao.png',
          tooltip: '',
          image: '',
          disabled: false,
        },
        {
          label: '撕白页',
          value: '撕白页',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E6%92%95%E7%99%BD%E9%A1%B5-%E7%A4%BA%E4%BE%8B%E5%9B%BE.jpg',
          tooltip: '如果实际内页P数为2P倍数，请选择此工艺下单',
          image: '',
          disabled: false,
        },
        {
          label: '整本打圆孔',
          value: '整本打圆孔',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/jiaoyinhuace_dayuankong.png',
          tooltip: '1个孔',
          image: '',
          disabled: false,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
    },
    id: 'mcheckbox82855',
    key: 77276,
    icon: 'checkbox-field',
    formItemFlag: true,
  },
  {
    key: 100257,
    formItemFlag: true,
    icon: 'radio-field',
    options: {
      customClass: '',
      defaultValue: null,
      desc: '',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '参样工艺',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'mradio43757',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '返单跟样',
          value: '返单跟样',
          exampleImage: '',
          tooltip: '是指之前在本厂印刷过相同文件和相同材质的订单,并且样品在公司留样。当选择"翻单跟样"时，需输入原样的订单号。注：仅支持跟样近3个月内订单。',
          image: '',
          additionalOption: null,
          hasAdditionalComponents: true,
          disabled: false,
          hidden: false,
          additionalComponents: [
            {
              id: 46814,
              label: '订单号',
              name: 'orderNo',
              type: 'input',
              required: false,
              defaultValue: '',
              placeholder: '订单号',
              options: [],
              simpleOptions: [],
            },
          ],
          additionalComponentsMultiple: false,
          maxAdditionalComponents: 3,
        },
        {
          label: '需车间留样',
          value: '需车间留样',
          exampleImage: '',
          tooltip: '是指下单后，想要把此订单留样在车间，以便于后期翻单跟样使用，可以点可选“需车间留样”。',
          image: '',
          additionalOption: null,
        },
        {
          label: '自带样',
          value: '自带样',
          exampleImage: '',
          tooltip: '温馨提示：如果需要寄样请联系客服索取收件信息！',
          image: '',
          additionalOption: null,
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
    },
    type: 'm-radio',
    id: 'mradio43757',
  },
  {
    type: 'm-checkbox',
    options: {
      customClass: [],
      defaultValue: [],
      desc: '复选框组件，用于在多个选项中选择多个',
      direction: 'horizontal',
      disabled: false,
      dsEnabled: false,
      dsName: '',
      hidden: false,
      iconSize: '20',
      label: '其它工艺',
      labelAlign: '',
      labelHidden: false,
      labelIconPosition: 'rear',
      labelKey: 'label',
      labelTooltip: null,
      labelWidth: null,
      name: 'otherProcess',
      onChange: '',
      onCreated: '',
      onMounted: '',
      onValidate: '',
      optionItems: [
        {
          label: '只印刷不装订',
          value: '只印刷不装订',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: false,
          hasAdditionalComponents: true,
          hidden: false,
          additionalComponents: [
            {
              id: 80717,
              label: '',
              name: 'onlyPrint',
              type: 'select',
              required: false,
              defaultValue: '',
              placeholder: '',
              options: [
                {
                  id: 95899,
                  label: '类型',
                  isGroup: true,
                  children: [
                    {
                      id: 53201,
                      label: '裁成品',
                      value: '裁成品',
                      isGroup: false,
                    },
                    {
                      id: 76113,
                      label: '毛料交货',
                      value: '毛料交货',
                      isGroup: false,
                    },
                    {
                      id: 64327,
                      label: '保留三边出血',
                      value: '保留三边出血',
                      isGroup: false,
                    },
                  ],
                },
              ],
              simpleOptions: [],
            },
          ],
          additionalComponentsMultiple: false,
          maxAdditionalComponents: 3,
        },
        {
          label: '特殊打包要求',
          value: '特殊打包要求',
          exampleImage: '',
          tooltip: '温馨提醒：请上传具体的打包要求，工期和价格复核时会主动联系您',
          image: '',
          disabled: false,
          hasAdditionalComponents: true,
          hidden: false,
          additionalComponents: [
            {
              id: 76271,
              label: '',
              name: 'count',
              type: 'input',
              required: false,
              defaultValue: '',
              placeholder: '包数',
              options: [],
              simpleOptions: [],
              maxLength: 100,
              inputType: 'number',
            },
            {
              id: 18647,
              label: '',
              name: 'memo',
              type: 'input',
              required: false,
              defaultValue: '',
              placeholder: '备注信息',
              options: [],
              simpleOptions: [],
            },
          ],
          additionalComponentsMultiple: false,
          maxAdditionalComponents: 3,
        },
        {
          label: '塑封',
          value: '塑封',
          exampleImage: '',
          tooltip: '',
          image: '',
          disabled: true,
        },
        {
          label: '套OPP袋',
          value: '套OPP袋',
          exampleImage: 'https://files.sd2000.com:9600/piscp/craft/huace/%E5%A5%97OPP%E8%A2%8B%E7%A4%BA%E4%BE%8B%E5%9B%BE.jpg',
          tooltip: '',
          image: '',
          disabled: false,
          hasAdditionalOption: true,
          hidden: false,
          additionalLabel: '请选择',
          additionalType: 'select',
          additionalOptions: '选项1,选项1\n选项2,选项2',
        },
      ],
      enableAdditionalOption: false,
      additionalOptionConfig: {
        enabled: false,
        label: '附加选项',
        placeholder: '请选择',
        type: 'select',
        options: [],
        triggerValues: [],
        min: 0,
        max: 999999,
        step: 1,
      },
      readonly: false,
      required: false,
      requiredHint: '',
      showImageSelect: false,
      valueKey: 'value',
      dataName: null,
    },
    id: 'mcheckbox99735',
    key: 72169,
    icon: 'checkbox-field',
    formItemFlag: true,
  },
  {
    key: 38928,
    category: 'container',
    icon: 'grid-sub-form',
    options: {
      actionColumnPosition: 'left',
      customClass: [],
      hidden: false,
      name: 'msubform33589',
      label: '封皮',
      onSubFormRowAdd: '',
      onSubFormRowChange: '',
      onSubFormRowDelete: '',
      onSubFormRowInsert: '',
      showBlankRow: true,
      showRowNumber: true,
    },
    type: 'm-sub-form',
    widgetList: [
      {
        key: 55045,
        formItemFlag: true,
        icon: 'cascader-field',
        options: {
          childrenKey: 'children',
          clearable: true,
          customClass: [],
          customRule: '',
          customRuleHint: '',
          desc: '',
          defaultValue: [],
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          label: '材料',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          levels: 2,
          multiple: false,
          name: 'mcascader82789',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '铜版纸',
              value: '铜版纸',
              desc: '',
              children: [
                {
                  label: '铜版纸250克',
                  value: 250,
                  desc: '厚度23丝左右',
                },
                {
                  label: '铜版纸157克',
                  value: 157,
                  desc: '厚度13丝左右',
                },
                {
                  label: '铜版纸128克',
                  value: 128,
                  desc: '厚度10丝左右',
                },
                {
                  label: '铜版纸105克',
                  value: 105,
                  desc: '厚度8.5丝左右',
                },
                {
                  label: '铜版纸200克',
                  value: 200,
                  desc: '厚度17丝左右',
                },
                {
                  label: '铜版纸300克',
                  value: 300,
                  desc: '厚度27丝左右',
                },
              ],
            },
            {
              label: '哑粉纸',
              value: '哑粉纸',
              desc: '',
              children: [
                {
                  label: '哑粉纸128克',
                  value: 128,
                  desc: '厚度11丝左右',
                },
                {
                  label: '哑粉纸157克',
                  value: 157,
                  desc: '厚度13丝左右',
                },
                {
                  label: '哑粉纸200克',
                  value: 200,
                  desc: '厚度17丝左右',
                },
                {
                  label: '哑粉纸250克',
                  value: 250,
                  desc: '厚度23丝左右',
                },
              ],
            },
            {
              label: '双胶纸',
              value: '双胶纸',
              desc: '',
              children: [
                {
                  label: '双胶纸高白80克',
                  value: 80,
                  desc: '厚度9丝左右',
                },
                {
                  label: '双胶纸高白70克',
                  value: 70,
                  desc: '厚度8.5丝左右',
                },
                {
                  label: '双胶纸高白100克',
                  value: 100,
                  desc: '厚度12丝左右',
                },
                {
                  label: '双胶纸高白120克',
                  value: 120,
                  desc: '厚度14丝左右',
                },
                {
                  label: '双胶纸米白80克',
                  value: 80,
                  desc: '厚度9丝左右',
                },
              ],
            },
            {
              label: '珠光纸',
              value: '珠光纸',
              desc: '精品纸',
              children: [
                {
                  label: '冰白纸240克',
                  value: 240,
                  desc: '30丝左右',
                },
                {
                  label: '棕宝星230克',
                  value: 230,
                  desc: '29丝左右',
                },
              ],
            },
            {
              label: '精品纸',
              value: '精品纸',
              desc: '',
              children: [
                {
                  label: '新美感高白120克',
                  value: 120,
                  desc: '厚度15丝左右',
                },
                {
                  label: '新美感高白150克',
                  value: 150,
                  desc: '厚度18丝左右',
                },
                {
                  label: '新美感高白210克',
                  value: 210,
                  desc: '厚度25丝左右',
                },
              ],
            },
          ],
          placeholder: '',
          readonly: false,
          required: false,
          requiredHint: '',
          size: '',
          valueKey: 'value',
          dataName: 'meterial',
        },
        type: 'm-cascader',
        id: 'mcascader82789',
      },
      {
        key: 93113,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: [],
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印面',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio80252',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '双面',
              value: 1,
              exampleImage: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E5%8F%8C%E9%9D%A2.jpg',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面',
              value: 2,
              exampleImage: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E5%8D%95%E9%9D%A2.jpg',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '不印',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
          dataName: null,
        },
        type: 'm-radio',
        id: 'mradio80252',
      },
      {
        key: 93113,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印色',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio103229',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '彩色',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单黑',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '四色加1专',
              value: 3,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E4%B8%93%E8%89%B2-%E4%B8%93%E8%89%B2%E5%8D%B0-%E5%9B%9B%E8%89%B2%E5%8A%A01%E4%B8%93-%E5%9B%9B%E8%89%B2%E5%8A%A02%E4%B8%93-%E4%B8%89%E8%89%B2%E5%8A%A02%E4%B8%9320241129.jpg',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio103229',
      },
      {
        key: 88464,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: [],
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '封皮工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox78929',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '模切',
              value: 1,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/huace_moqie_20220630_1.png',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '击凸',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
              hasAdditionalComponents: true,
              disabled: false,
              hidden: false,
              additionalComponents: [
                {
                  id: 76919,
                  label: '颜色',
                  name: 'color',
                  type: 'select',
                  required: true,
                  defaultValue: '',
                  placeholder: '',
                  options: [
                    {
                      id: 8151,
                      label: '有色',
                      value: 'color',
                      isGroup: false,
                    },
                    {
                      id: 21396,
                      label: '无色',
                      value: 'nocolor',
                      isGroup: false,
                    },
                  ],
                  simpleOptions: [],
                },
                {
                  id: 92352,
                  label: '长边',
                  name: 'longside',
                  type: 'input',
                  required: true,
                  defaultValue: '',
                  placeholder: '长边(MM)',
                  options: [],
                  simpleOptions: [],
                },
                {
                  id: 62136,
                  label: '短边',
                  name: 'shortside',
                  type: 'input',
                  required: true,
                  defaultValue: '',
                  placeholder: '短边(MM)',
                  options: [],
                  simpleOptions: [],
                },
              ],
              additionalComponentsMultiple: true,
              maxAdditionalComponents: 2,
            },
            {
              label: '压凹',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
              hasAdditionalComponents: true,
              disabled: false,
              hidden: false,
              additionalComponents: [
                {
                  id: 76919,
                  label: '',
                  name: 'color',
                  type: 'select',
                  required: true,
                  defaultValue: '',
                  placeholder: '',
                  options: [
                    {
                      id: 8151,
                      label: '有色',
                      value: 'color',
                      isGroup: false,
                    },
                    {
                      id: 21396,
                      label: '无色',
                      value: 'nocolor',
                      isGroup: false,
                    },
                  ],
                  simpleOptions: [],
                },
                {
                  id: 92352,
                  label: '',
                  name: 'longside',
                  type: 'input',
                  required: true,
                  defaultValue: '',
                  placeholder: '长边(MM)',
                  options: [],
                  simpleOptions: [],
                },
                {
                  id: 62136,
                  label: '',
                  name: 'shortside',
                  type: 'input',
                  required: true,
                  defaultValue: '',
                  placeholder: '短边(MM)',
                  options: [],
                  simpleOptions: [],
                },
              ],
              additionalComponentsMultiple: true,
              maxAdditionalComponents: 2,
            },
            {
              label: '打码',
              value: 4,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/danye_dama_20220608.jpg',
              tooltip: '温馨提醒:封面打一个码，最多可循环打码2次，起始码请输入7位数字',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
              hasAdditionalComponents: true,
              additionalComponents: [
                {
                  id: 19768,
                  label: '',
                  name: '类型',
                  type: 'select',
                  required: true,
                  defaultValue: '',
                  placeholder: '类型',
                  options: [
                    {
                      id: 102833,
                      label: '类型',
                      isGroup: true,
                      children: [
                        {
                          id: 100242,
                          label: '单次打码',
                          value: 'single',
                          isGroup: false,
                        },
                        {
                          id: 84735,
                          label: '循环两次打码',
                          value: 'double',
                          isGroup: false,
                        },
                      ],
                    },
                  ],
                  simpleOptions: [],
                  requiredMessage: '类型必填',
                },
                {
                  id: 29075,
                  label: '',
                  name: '颜色',
                  type: 'select',
                  required: true,
                  defaultValue: '',
                  placeholder: '颜色',
                  options: [
                    {
                      id: 99144,
                      label: '颜色',
                      isGroup: true,
                      children: [
                        {
                          id: 21250,
                          label: '红色',
                          value: 'red',
                          isGroup: false,
                        },
                        {
                          id: 89460,
                          label: '黑色',
                          value: 'black',
                          isGroup: false,
                        },
                        {
                          id: 17290,
                          label: '按文件设计颜色',
                          value: 'design',
                          isGroup: false,
                        },
                      ],
                    },
                  ],
                  simpleOptions: [],
                  requiredMessage: '颜色必填',
                },
                {
                  id: 29037,
                  label: '',
                  name: '是否NO',
                  type: 'select',
                  required: true,
                  defaultValue: '',
                  placeholder: '是否带NO',
                  options: [
                    {
                      id: 54318,
                      label: '是否带NO',
                      isGroup: true,
                      children: [
                        {
                          id: 43241,
                          label: '带NO.',
                          value: '1',
                          isGroup: false,
                        },
                        {
                          id: 109200,
                          label: '不带',
                          value: '0',
                          isGroup: false,
                        },
                      ],
                    },
                  ],
                  simpleOptions: [],
                },
                {
                  id: 113370,
                  label: '',
                  name: '起始码',
                  type: 'input',
                  required: true,
                  defaultValue: '',
                  placeholder: '起始码',
                  options: [],
                  simpleOptions: [],
                  inputType: 'text',
                },
              ],
              additionalComponentsMultiple: false,
              maxAdditionalComponents: 3,
            },
            {
              label: '局部UV',
              value: 5,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E5%B1%80%E9%83%A8UV20240716.png',
              tooltip: '适合大批量',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '单面压纹',
              value: 6,
              exampleImage: '',
              tooltip: 'https://files.sd2000.com:9600/piscp/craft/jiaoyinhuace_yawen_20211025.jpg',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '封面封底勒口',
              value: 7,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/shumahuace_leikou_20220210.jpg',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '封底封套',
              value: 8,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E7%94%BB%E5%86%8C-%E5%B0%81%E5%BA%95%E5%8A%A0%E5%B0%81%E5%A5%9720241018.jpg',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '多款封面',
              value: 9,
              exampleImage: '',
              tooltip: '1、内页完全共用，封面多款，可选择“多款封面”2、最多可支持4款封面，根据您的实际需求填写每款数量',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
          dataName: null,
        },
        type: 'm-checkbox',
        id: 'mcheckbox78929',
      },
      {
        key: 88464,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: [],
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '覆膜过油工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox16669',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '单面哑膜',
              value: '单面哑膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面亮膜',
              value: '单面亮膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面防刮伤哑膜',
              value: '单面防刮伤哑膜',
              exampleImage: '',
              tooltip: '黑色/重底色印刷建议做防刮伤膜减轻划痕情况',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面触感膜',
              value: '单面触感膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '单面触感膜',
              value: '单面触感膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '单面光油',
              value: '单面光油',
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
            {
              label: '单面哑油',
              value: '单面哑油',
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
              hidden: false,
              additionalLabel: '',
              additionalType: '',
              additionalOptions: '',
              additionalPlaceholder: '',
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
          dataName: null,
        },
        type: 'm-checkbox',
        id: 'mcheckbox16669',
      },
      {
        key: 88464,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '烫印工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox97184',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '浮雕烫',
              value: '浮雕烫',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '热烫',
              value: '热烫',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox97184',
      },
      {
        key: 88464,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '其它工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox19662',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '现调纸',
              value: '现调纸',
              exampleImage: '',
              tooltip: '您需要详细描述：纸张材质、克数、纸张颜色；比如：美兰尼桑,120g, 自然白',
              image: '',
              additionalOption: null,
            },
            {
              label: '异常处理',
              value: '异常处理',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '印刷机型',
              value: '印刷机型',
              exampleImage: '',
              tooltip: '喷墨轮转机 价格更低！！！',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox19662',
      },
      {
        key: 88464,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '数字增效',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox102264',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '立体UV',
              value: '立体UV',
              exampleImage: '',
              tooltip: '适合小面积、小批量',
              image: '',
              additionalOption: null,
            },
            {
              label: '立体冷烫',
              value: '立体冷烫',
              exampleImage: '',
              tooltip: '适合小面积、小批量',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox102264',
      },
    ],
    id: 'msubform33589',
  },
  {
    key: 48972,
    category: 'container',
    options: {
      actionColumnPosition: 'left',
      customClass: [],
      hidden: false,
      name: 'msubform57643',
      label: '内页',
      onSubFormRowAdd: '',
      onSubFormRowChange: '',
      onSubFormRowDelete: '',
      onSubFormRowInsert: '',
      showBlankRow: true,
      showRowNumber: true,
    },
    type: 'm-sub-form',
    widgetList: [
      {
        key: 65900,
        options: {
          childrenKey: 'children',
          clearable: true,
          customClass: [],
          customRule: '',
          customRuleHint: '',
          desc: '',
          defaultValue: [],
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          label: '材料',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          levels: 2,
          multiple: false,
          name: 'mcascader56274',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: 'select 1',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: 'select 2',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: 'select 3',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
          ],
          placeholder: '',
          readonly: false,
          required: false,
          requiredHint: '',
          size: '',
          valueKey: 'value',
          dataName: 'meterial',
        },
        type: 'm-cascader',
        id: 'mcascader56274',
        icon: 'cascader-field',
        formItemFlag: true,
      },
      {
        key: 61914,
        options: {
          customClass: [],
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印面',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio64100',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '双面',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '单面',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '不印',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
          dataName: null,
        },
        type: 'm-radio',
        id: 'mradio64100',
        icon: 'radio-field',
        formItemFlag: true,
      },
      {
        key: 61914,
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印色',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio64614',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '彩色',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '单黑',
              value: 2,
              exampleImage: 'https://files.sd2000.com:9600/piscp/shiyitu/huace/%E5%8D%95%E9%BB%91.jpg',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '四色加1专',
              value: 3,
              exampleImage: 'https://files.sd2000.com:9600/piscp/craft/%E4%B8%93%E8%89%B2-%E4%B8%93%E8%89%B2%E5%8D%B0-%E5%9B%9B%E8%89%B2%E5%8A%A01%E4%B8%93-%E5%9B%9B%E8%89%B2%E5%8A%A02%E4%B8%93-%E4%B8%89%E8%89%B2%E5%8A%A02%E4%B8%9320241129.jpg',
              tooltip: '',
              image: '',
              disabled: false,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio64614',
        icon: 'radio-field',
        formItemFlag: true,
      },
      {
        key: 106844,
        options: {
          appendButton: false,
          appendButtonDisabled: false,
          appendButtonIcon: 'search',
          appendButtonLabel: '',
          appendButtonType: 'primary',
          clearable: true,
          customClass: '',
          defaultValue: null,
          desc: '',
          disabled: false,
          hidden: false,
          inputAlign: 'left',
          label: 'P数',
          labelAlign: '',
          labelHidden: false,
          labelWidth: null,
          leftIcon: '',
          maxLength: null,
          name: 'minput108262',
          onAppendButtonClick: '',
          onBlur: '',
          onChange: '',
          onCreated: '',
          onFocus: '',
          onInput: '',
          onMounted: '',
          onValidate: '',
          placeholder: '',
          readonly: false,
          required: false,
          requiredHint: '',
          rightIcon: '',
          showWordLimit: false,
          size: '',
          type: 'text',
          validation: '',
          validationHint: '',
        },
        type: 'm-input',
        id: 'minput108262',
        icon: 'text-field',
        formItemFlag: true,
      },
      {
        key: 61914,
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '内容一样',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio53284',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '是',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '否',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio53284',
        icon: 'radio-field',
        formItemFlag: true,
      },
      {
        key: 25971,
        options: {
          customClass: [],
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '其它工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox53434',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '现调纸',
              value: 1,
              exampleImage: '',
              tooltip: '您需要详细描述：纸张材质、克数、纸张颜色；比如：美兰尼桑,120g, 自然白',
              image: '',
              disabled: false,
            },
            {
              label: '头对尾',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '头对头',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              disabled: false,
            },
            {
              label: '印刷机型',
              value: 4,
              exampleImage: '',
              tooltip: '喷墨轮转机 价格更低！！！',
              image: '',
              disabled: false,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox53434',
        icon: 'checkbox-field',
        formItemFlag: true,
      },
    ],
    id: 'msubform57643',
    icon: 'grid-sub-form',
  },
  {
    key: 80145,
    category: 'container',
    icon: 'grid-sub-form',
    options: {
      actionColumnPosition: 'left',
      customClass: [],
      hidden: false,
      name: 'msubform85695',
      label: '拉页',
      onSubFormRowAdd: '',
      onSubFormRowChange: '',
      onSubFormRowDelete: '',
      onSubFormRowInsert: '',
      showBlankRow: false,
      showRowNumber: true,
    },
    type: 'm-sub-form',
    widgetList: [
      {
        key: 89637,
        formItemFlag: true,
        icon: 'cascader-field',
        options: {
          childrenKey: 'children',
          clearable: true,
          customClass: [],
          customRule: '',
          customRuleHint: '',
          desc: '',
          defaultValue: [],
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          label: '材料',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          levels: 2,
          multiple: false,
          name: 'mcascader68227',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              children: [
                {
                  label: 'child 1',
                  value: 11,
                },
              ],
              label: 'select 1',
              value: 1,
            },
            {
              label: 'select 2',
              value: 2,
            },
            {
              label: 'select 3',
              value: 3,
            },
          ],
          placeholder: '',
          readonly: false,
          required: false,
          requiredHint: '',
          size: '',
          valueKey: 'value',
          dataName: 'meterial',
        },
        type: 'm-cascader',
        id: 'mcascader68227',
      },
      {
        key: 61909,
        formItemFlag: true,
        icon: 'size-field',
        options: {
          customClass: [],
          defaultValue: {
            width: '',
            height: '',
          },
          disabled: false,
          hidden: false,
          label: '展开尺寸',
          labelAlign: '',
          labelHidden: false,
          labelWidth: null,
          name: 'msize33069',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          readonly: false,
          required: false,
          requiredHint: '',
          validation: '',
          validationHint: '',
          widthPlaceholder: '请输入宽度(MM)',
          heightPlaceholder: '请输入高度(MM)',
          clearable: true,
          inputAlign: 'left',
          size: '',
          onChange: '',
          onBlur: '',
          onFocus: '',
          onInput: '',
          desc: '高度（装订边）与成品高度（装订边）须保持一致，宽度大于成品宽度小于等于840MM',
        },
        type: 'm-size',
        id: 'msize33069',
      },
      {
        key: 87025,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印面',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio93442',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '双面',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '不印',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio93442',
      },
      {
        key: 87025,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '印色',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio96673',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '彩色',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单黑',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '四色加1专',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio96673',
      },
      {
        key: 95846,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          hidden: false,
          iconSize: '20',
          label: '其他工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox65382',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: 'check 1',
              value: 1,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: 'check 2',
              value: 2,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: 'check 3',
              value: 3,
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox65382',
      },
    ],
    id: 'msubform85695',
  },
  {
    key: 80145,
    category: 'container',
    icon: 'grid-sub-form',
    options: {
      actionColumnPosition: 'left',
      customClass: '',
      hidden: false,
      name: 'msubform56380',
      label: '护封',
      onSubFormRowAdd: '',
      onSubFormRowChange: '',
      onSubFormRowDelete: '',
      onSubFormRowInsert: '',
      showBlankRow: false,
      showRowNumber: true,
    },
    type: 'm-sub-form',
    widgetList: [
      {
        key: 61423,
        formItemFlag: true,
        icon: 'cascader-field',
        options: {
          childrenKey: 'children',
          clearable: true,
          customClass: '',
          customRule: '',
          customRuleHint: '',
          desc: '',
          defaultValue: [],
          disabled: false,
          dsEnabled: false,
          dataName: 'meterial',
          dsName: '',
          hidden: false,
          label: '材料',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          levels: 2,
          multiple: false,
          name: 'mcascader71448',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              children: [
                {
                  label: 'child 1',
                  value: 11,
                },
              ],
              label: 'select 1',
              value: 1,
            },
            {
              label: 'select 2',
              value: 2,
            },
            {
              label: 'select 3',
              value: 3,
            },
          ],
          placeholder: '',
          readonly: false,
          required: false,
          requiredHint: '',
          size: '',
          valueKey: 'value',
        },
        type: 'm-cascader',
        id: 'mcascader71448',
      },
      {
        key: 66932,
        formItemFlag: true,
        icon: 'size-field',
        options: {
          desc: '高度不能高于成品高度，宽度最大840MM，不含书脊！',
          customClass: '',
          defaultValue: {
            width: '',
            height: '',
          },
          disabled: false,
          hidden: false,
          label: '展开尺寸',
          labelAlign: '',
          labelHidden: false,
          labelWidth: null,
          name: 'msize90487',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          readonly: false,
          required: false,
          requiredHint: '',
          validation: '',
          validationHint: '',
          widthPlaceholder: '高度(装订边)',
          heightPlaceholder: '宽度',
          clearable: true,
          inputAlign: 'left',
          size: '',
          onChange: '',
          onBlur: '',
          onFocus: '',
          onInput: '',
        },
        type: 'm-size',
        id: 'msize90487',
      },
      {
        key: 76608,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '印面',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio71264',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '双面',
              value: '双面',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面',
              value: '单面',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '不印',
              value: '不印',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio71264',
      },
      {
        key: 76608,
        formItemFlag: true,
        icon: 'radio-field',
        options: {
          customClass: '',
          defaultValue: null,
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '印色',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mradio105288',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '彩色',
              value: '彩色',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '四色加1专',
              value: '四色加1专',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-radio',
        id: 'mradio105288',
      },
      {
        key: 13237,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '覆膜过油工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox8174',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '单面哑膜',
              value: '单面哑膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面亮膜',
              value: '单面亮膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '单面星光膜',
              value: '单面星光膜',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox8174',
      },
      {
        key: 13237,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [2],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '数字增效',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox32166',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '立体冷烫',
              value: '立体冷烫',
              exampleImage: '',
              tooltip: '适合小面积、小批量',
              image: '',
              additionalOption: null,
            },
            {
              label: '立体UV',
              value: '立体UV',
              exampleImage: '',
              tooltip: '适合小面积、小批量',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox32166',
      },
      {
        key: 13237,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '封皮工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox44415',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '模切',
              value: '模切',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '局部Uv',
              value: '局部Uv',
              exampleImage: '',
              tooltip: '适合大批量',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox44415',
      },
      {
        key: 13237,
        formItemFlag: true,
        icon: 'checkbox-field',
        options: {
          customClass: '',
          defaultValue: [],
          desc: '',
          direction: 'horizontal',
          disabled: false,
          dsEnabled: false,
          dsName: '',
          dataName: '',
          hidden: false,
          iconSize: '20',
          label: '烫印工艺',
          labelAlign: '',
          labelHidden: false,
          labelIconPosition: 'rear',
          labelKey: 'label',
          labelTooltip: null,
          labelWidth: null,
          name: 'mcheckbox93212',
          onChange: '',
          onCreated: '',
          onMounted: '',
          onValidate: '',
          optionItems: [
            {
              label: '浮雕烫',
              value: '浮雕烫',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
            {
              label: '热烫',
              value: '热烫',
              exampleImage: '',
              tooltip: '',
              image: '',
              additionalOption: null,
            },
          ],
          enableAdditionalOption: false,
          additionalOptionConfig: {
            enabled: false,
            label: '附加选项',
            placeholder: '请选择',
            type: 'select',
            options: [],
            triggerValues: [],
            min: 0,
            max: 999999,
            step: 1,
          },
          readonly: false,
          required: false,
          requiredHint: '',
          showImageSelect: false,
          valueKey: 'value',
        },
        type: 'm-checkbox',
        id: 'mcheckbox93212',
      },
    ],
    id: 'msubform56380',
  },
  {
    key: 111287,
    formItemFlag: false,
    icon: 'static-text',
    options: {
      customClass: ['content-title'],
      desc: '',
      fontSize: '16px',
      hidden: false,
      name: 'static-number',
      onCreated: '',
      onMounted: '',
      textContent: '数量',
      label: 'm-static-text',
    },
    type: 'm-static-text',
    id: 'mstatictext18115',
  },
  {
    key: 114037,
    formItemFlag: false,
    icon: 'button',
    options: {
      customClass: [],
      desc: '',
      displayStyle: 'block',
      hidden: false,
      label: '报价组件',
      name: 'mquote97518',
      onCreated: '',
      onMounted: '',
      quantities: [10, 20, 50, 200, 300],
      showOfficialOrder: true,
      showManualOrder: true,
      quoteApiUrl: '/api/quote',
    },
    type: 'm-quote',
    id: 'mquote97518',
  },
]
