export default {
  type: 'm-checkbox',
  icon: 'checkbox-field',
  formItemFlag: true,
  options: {
    name: 'mcheckbox90129',
    label: 'm-checkbox dataset',
    labelAlign: '',
    defaultValue: [],
    iconSize: '20',
    direction: 'horizontal',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    dsEnabled: true,
    dsName: 'dsTest2',
    labelKey: 'Key',
    valueKey: 'Value',
    dataSetName: 'dataSet',
    optionItems: [
      { label: 'check 1', value: 1 },
      { label: 'check 2', value: 2 },
      { label: 'check 3', value: 3 },
    ],
    required: false,
    requiredHint: '',
    customClass: [],
    labelIconPosition: 'rear',
    labelTooltip: null,
  },
  id: 'mcheckbox90129',
}
