export default {
  type: 'm-datetime',
  icon: 'date-field',
  formItemFlag: true,
  options: {
    name: 'mdatetime36197',
    label: 'm-datetime',
    labelAlign: '',
    defaultValue: null,
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    clearable: true,
    editable: false,
    format: 'YYYY-MM-DD HH:mm:ss',
    minDate: '',
    maxDate: '',
    required: true,
    requiredHint: '',
    validation: '',
    validationHint: '',
    customClass: [],
    labelIconClass: null,
    labelIconPosition: 'rear',
    labelTooltip: null,
    onCreated: '',
    onMounted: '',
    onConfirm: '',
    onValidate: '',
  },
  id: 'mdate36197',
}
