export default {
  type: 'm-file-upload',
  icon: 'file-upload-field',
  formItemFlag: true,
  options: {
    name: 'mfileupload37776',
    label: 'm-file-upload',
    labelAlign: '',
    labelWidth: null,
    labelHidden: false,
    uploadTip: '',
    withCredentials: false,
    multipleSelect: false,
    disabled: false,
    readonly: false,
    hidden: false,
    required: false,
    requiredHint: '',
    customRule: '',
    customRuleHint: '',
    uploadURL: "DSV.api+'File/upload/demo/file?token='+DSV.token",
    limit: 3,
    fileMaxSize: 5,
    fileTypes: ['png', 'jpg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip'],
    customClass: '',
    labelIconPosition: 'rear',
    labelTooltip: null,
    onCreated: '',
    onMounted: '',
    onBeforeUpload: '',
    onUploadSuccess: '',
    onUploadError: '',
    onFileRemove: '',
    onValidate: '',
  },
  id: 'mfileupload37776',
}
