export default {
  type: 'm-input',
  icon: 'text-field',
  formItemFlag: true,
  options: {
    name: 'minput104177',
    label: 'm-input',
    labelAlign: '',
    type: 'text',
    defaultValue: 'input default value',
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    inputAlign: 'left',
    readonly: false,
    disabled: false,
    hidden: false,
    clearable: true,
    required: true,
    requiredHint: '请输入m-input的内容',
    validation: '',
    validationHint: '',
    customClass: [],
    maxLength: null,
    showWordLimit: false,
    leftIcon: '',
    rightIcon: '',
    appendButton: false,
    appendButtonType: 'primary',
    appendButtonLabel: '',
    appendButtonIcon: 'search',
    appendButtonDisabled: false,
    onCreated: '',
    onMounted: '',
    onInput: '',
    onFocus: '',
    onBlur: '',
    onAppendButtonClick: '',
    onValidate: '',
  },
  id: 'minput104177',
}
