export default {
  type: 'm-number',
  icon: 'number-field',
  formItemFlag: true,
  options: {
    name: 'mnumber53688',
    label: 'm-number',
    labelAlign: '',
    defaultValue: null,
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    required: true,
    requiredHint: '请输入数字',
    validation: '',
    validationHint: '请输入正确的数字',
    customClass: [],
    labelIconClass: null,
    labelIconPosition: 'rear',
    labelTooltip: null,
  },
  id: 'mnumber53688',
}
