export default {
  type: 'm-picture-upload',
  icon: 'picture-upload-field',
  formItemFlag: true,
  options: {
    name: 'mpictureupload32034',
    label: 'm-picture-upload',
    labelAlign: '',
    labelWidth: null,
    labelHidden: false,
    uploadTip: '',
    withCredentials: false,
    multipleSelect: false,
    disabled: false,
    hidden: false,
    required: false,
    requiredHint: '',
    customRule: '',
    readonly: false,
    customRuleHint: '',
    uploadURL: 'https://demo-api.vmform.srvcloud.cn/File/upload/demo/picture',
    limit: 6,
    fileMaxSize: 5,
    fileTypes: ['jpg', 'jpeg', 'png'],
    customClass: [],
    labelIconPosition: 'rear',
    labelTooltip: null,
    onCreated: '',
    onMounted: '',
    onBeforeUpload: '',
    onUploadSuccess: '',
    onUploadError: '',
    onFileRemove: '',
    onValidate: '',
  },
  id: 'mpictureupload32034',
}
