export default {
  type: 'm-radio',
  icon: 'radio-field',
  formItemFlag: true,
  options: {
    name: 'mradio62090',
    label: 'm-radio',
    labelAlign: '',
    defaultValue: null,
    iconSize: 20,
    direction: 'horizontal',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    dsEnabled: false,
    dsName: 'dsTest',
    labelKey: 'label',
    valueKey: 'value',
    // "labelKey": "summary",
    // "valueKey": "temperatureC",
    optionItems: [
      {
        label: 'radio 1',
        value: 1,
      },
      {
        label: 'radio 2',
        value: 2,
      },
      {
        label: 'radio 3',
        value: 3,
      },
    ],
    required: false,
    requiredHint: '',
    customClass: [],
    labelIconClass: null,
    labelIconPosition: 'rear',
    labelTooltip: null,
    onCreated: '',
    onMounted: '',
    onChange: '',
    onValidate: '',
  },
  id: 'mradio51288',
}
