export default {
  type: 'm-rate',
  icon: 'rate-field',
  formItemFlag: true,
  options: {
    name: 'mrate27830',
    label: 'm-rate',
    labelAlign: '',
    defaultValue: 0,
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    required: false,
    requiredHint: '',
    validation: '',
    validationHint: '',
    customClass: '',
    labelIconPosition: 'rear',
    labelTooltip: null,
    max: 5,
    allowHalf: true,
    showScore: true,
  },
  id: 'mrate27830',
}
