export default {
  key: 95861,
  type: 'm-select',
  icon: 'select-field',
  formItemFlag: true,
  options: {
    name: 'mselect71412',
    label: 'm-select datasource',
    labelAlign: '',
    defaultValue: '',
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    dsEnabled: true,
    dsName: 'dsTest',
    labelKey: 'Key',
    valueKey: 'Value',
    optionItems: [
      { label: 'select 1', value: 1 },
      { label: 'select 2', value: 2 },
      { label: 'select 3', value: 3 },
    ],
    required: false,
    requiredHint: '',
    customClass: [],
    labelIconPosition: 'rear',
    labelTooltip: null,
  },
  id: 'mselect71412',
}
