export default {
  type: 'm-slider',
  icon: 'slider-field',
  formItemFlag: true,
  options: {
    name: 'mslider41067',
    label: 'm-slider',
    labelAlign: '',
    defaultValue: null,
    size: '',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    validation: '',
    validationHint: '',
    customClass: '',
    labelIconPosition: 'rear',
    labelTooltip: null,
    min: 0,
    max: 100,
    step: 10,
    range: false,
    height: null,
  },
  id: 'mslider41067',
}
