export default {
  type: 'm-stepper',
  icon: 'stepper-field',
  formItemFlag: true,
  options: {
    name: 'mstepper75345',
    label: 'm-stepper',
    labelAlign: '',
    readonly: false,
    defaultValue: '1',
    placeholder: '',
    stepButtonSize: '28',
    labelWidth: null,
    labelHidden: false,
    disabled: false,
    hidden: false,
    validation: '',
    validationHint: '',
    customClass: [],
    labelIconPosition: 'rear',
    labelTooltip: null,
    min: -100000000000,
    max: 100000000000,
    precision: 0,
    step: 3,
  },
  id: 'mstepper75345',
}
