export default {
  type: 'm-switch',
  icon: 'switch-field',
  formItemFlag: true,
  options: {
    name: 'mswitch102117',
    label: 'm-switch',
    labelAlign: '',
    defaultValue: false,
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    customClass: [],
    labelIconPosition: 'rear',
    labelTooltip: null,
    switchSize: 24,
    activeValue: true,
    inactiveValue: false,
    activeLabel: 'Switched On',
    inactiveLabel: 'Switched Off',
    activeColor: '#EC2424',
    inactiveColor: '#43BE7E',
  },
  id: 'mswitch102117',
}
