export default {
  type: 'm-textarea',
  icon: 'textarea-field',
  formItemFlag: true,
  options: {
    name: 'mtextarea64275',
    label: 'm-textarea',
    labelAlign: '',
    rows: 18,
    defaultValue: '',
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    inputAlign: 'left',
    readonly: false,
    disabled: false,
    hidden: false,
    required: false,
    requiredHint: '',
    validation: '',
    validationHint: '',
    customClass: [],
    maxLength: null,
    showWordLimit: false,
    onCreated: '',
    onMounted: '',
    onInput: '',
    onFocus: '',
    onBlur: '',
    onValidate: '',
  },
  id: 'mtextarea64275',
}
