export default {
  type: 'm-time',
  icon: 'time-field',
  formItemFlag: true,
  options: {
    name: 'mtime59299',
    label: 'm-time',
    labelAlign: '',
    defaultValue: null,
    placeholder: '',
    size: '',
    labelWidth: null,
    labelHidden: false,
    readonly: false,
    disabled: false,
    hidden: false,
    clearable: true,
    editable: false,
    required: true,
    requiredHint: '',
    validation: '',
    validationHint: '',
    format: 'HH时mm分',
    customClass: [],
    labelIconClass: null,
    labelIconPosition: 'rear',
    labelTooltip: null,
    onCreated: '',
    onMounted: '',
    onConfirm: '',
    onValidate: '',
  },
  id: 'mtime59299',
}
